### ISSUE TITLE
SOP/Streamline Data Return from S3

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/core-operations#24]
@Jeltje pointed out that the process for returning URLs for each data file to clients is 1) time consuming for her/client and 2) not secure since anyone with the URL can download data.

We'd like to update the download SOP (https://ucsc-cgl.atlassian.net/wiki/display/PROD/General+SOPs) to include download directions using s3cmd or a similar tool.  This would allow the cloud shepherd to give a client a prefix, e.g. s3://foo.bar/path/path/* and that would be expanded by the tool so users could download the content of this "directory".

**Comment by hannes-ucsc** [comment]
Trying to keep URLs secret does not provide sufficient privacy, or protection from excessive downloads at our cost. I propose that we make the destination bucket "requester pays" as well. That means that our customers need to setup an AWS account. For uploading they already need an account so I don't think this is too much to ask. Then we can freely publish the location of the outputs in tickets etc., because public access is disabled.

If @melissacline, @Jeltje, @dyollluap and @briandoconnor agree, I would like to change the SOP in that sense.

**Comment by hannes-ucsc** [comment]
Assigning to Melissa for verifying with customers if the proposed solution is acceptable.
